apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: demo
spec:
  containers:
  - name: mypod
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: my-vault-volume
      mountPath: "/etc/azure"
      readOnly: true
  serviceAccountName: azure-vault
  volumes:
    - name: my-vault-volume
      persistentVolumeClaim:
        claimName: csi-pvc-azure