apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-azure
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: vault-azure-storage