kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vault-azure-storage
  namespace: demo
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: secrets.csi.kubevault.com
parameters:
  ref: demo/vault-app
  engine: Azure
  role: my-role
  path: azure
  
